# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_to',
            field=models.DateField(),
        ),
    ]
